### ISSUE TITLE
[Bug] Detect folders when dragging-and-dropping files

### ISSUE THREAD

**Issue by lucasoshiro** [Future-Scholars/paperlib#515]
Hi! Just started using paperlib this week, amazing project!

I was importing the papers that I already have downloaded here and creating the same folder structure as they are currently (without Paperlib). I was expecting that when I drag-and-drop a file from the file manager to Paperlib it would add that file to the current folder, however, it adds to "All Papers" and I need to move manually to folder.

I'm using Mac OS Sonoma and Paperlib 3.0.10.

So, here's my feature request: when drag-and-dropping a file, add it to the current opened folder instead of "All Papers".

**Comment by GeoffreyChen777** [comment]
What is the current opened folder? The folder in filesystem or in Paperlib?

**Comment by GeoffreyChen777** [comment]
If you are talking about the folder in paperlib, try this:

<img width="583" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/14183213/33bb0f3f-efee-4b72-b68b-9c4a58cff751">

**Comment by lucasoshiro** [comment]
Thanks for you time @GeoffreyChen777 !

> What is the current opened folder? The folder in filesystem or in Paperlib?

In Paperlib. I was dropping here (currently, "My folder" was opened, and I dropped like this:

<img width="1120" alt="Captura de Tela 2024-04-28 às 17 49 24" src="https://github.com/Future-Scholars/paperlib/assets/12701580/4ed03dae-4b2b-4dcd-adb0-dae566f7e6d0">

After that, the was added but it only appeared in "All Papers". "My folder" didn't contain it.

> If you are talking about the folder in paperlib, try this:
> 
> <img alt="image" width="583" src="https://private-user-images.githubusercontent.com/14183213/326271937-33bb0f3f-efee-4b72-b68b-9c4a58cff751.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMzY5MjgsIm5iZiI6MTcxNDMzNjYyOCwicGF0aCI6Ii8xNDE4MzIxMy8zMjYyNzE5MzctMzNiYjBmM2YtZWZlZS00YjcyLWI2OGItOWM0YTU4Y2ZmNzUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDIwMzcwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3NzZhNTY0NGMyYjNhM2JhZmRhY2IyMzNlM2IyOTkyY2M5OTYyMzAzMTZjM2I1YmRjMWI2MTgxMjk2NWIyYWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.epbGbMbLI9pScEKiaLJY7dEPg156HtB2iqy6BclMftY">

It didn't work 🤔. I mean, even though I dropped it over the "My folder" icon on sidebar, Paperlib only adds the file to "All Papers"...

**Comment by GeoffreyChen777** [comment]
Hi, it must be a bug.

If you drag and drop it in the sidebar folder, the paper should be imported into this folder.

I'm on vacation, so I cannot fix this right now. But I will solve this when I'm back sorry.

**Comment by lucasoshiro** [comment]
> I'm on vacation, so I cannot fix this right now. But I will solve this when I'm back sorry.

No problem, enjoy it!

Just another extra information: I just tested it on Linux (Manjaro Linux), the same thing happens.

**Comment by GeoffreyChen777** [comment]
Fixed. Please wait for the next release.

**Comment by yangluo23** [comment]
Such bug still exists though.... 
OS: Windows11
Version: latest

**Comment by GeoffreyChen777** [comment]
> Such bug still exists though.... OS: Windows11 Version: latest

@yangluo23 cannot reproduce. Same OS. Try this:


<img width="583" alt="326271937-33bb0f3f-efee-4b72-b68b-9c4a58cff751" src="https://github.com/user-attachments/assets/27f29ba9-46ad-42ca-9c79-2fad08f5c3f1">

**Comment by yangluo23** [comment]
Yes, if such bug does not exist, it would be more comfortable. Now I need to carefully drag my papers to the right folder space~~

**Comment by GeoffreyChen777** [comment]
@yangluo23 Hi, what is the bug? You cannot import a paper into a folder via dragging them into the folder item in the left panel?

If you are talking about dragging a paper into the main view, and import them into the folder you choose in the left panel, I would say it's not a bug. It's a design.

The main view is showing the filtered result by queries you choose. For example, you choose a folder 'Folder1' and type something, for example 'keywords' in the searching bar. The main view is showing the results filtered by `folder.name == 'Folder1' and (title contains 'keywords' or authors contains 'keywords')`.

It means that, when you click 'Folder1' in the left panel, you are not really opening a real folder. It's just a filter query.

**Comment by yangluo23** [comment]
Got it, thanks!
